# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# roguetest test lavafort
# [templates.test_map]
# map_files = ["lavafort.dmm"]
# directory = "_maps/twilight_axis/templates/test/"
# required_map = "roguetest.dmm"
# coordinates = [1, 1, 1]

# dunworld witch huts
[templates.witch_hut]
map_files = ["witch_hut_1.dmm","witch_hut_2.dmm"]
directory = "_maps/twilight_axis/templates/dun_world/witch_hut/"
required_map = "dun_world.dmm"
coordinates = [194, 240, 1]

# rockhill bridges
[templates.bridge]
map_files = ["bridge1.dmm","bridge2.dmm","bridge3.dmm","bridge4.dmm","bridge5.dmm","bridge6.dmm","bridge7.dmm"]
directory = "_maps/twilight_axis/templates/rockhill/bridge/"
required_map = "rockhill.dmm"
coordinates = [145, 190, 1]
